"""
Django settings for vmstat project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "!28&%f@*%osruevm735&lgqi7&+nvt1(2c9m6l=9fsri0mdl74"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = ["vmapi"]

# MIDDLEWARE = ["vmapi.middlewares.put_middleware"]

ROOT_URLCONF = "vmstat.urls"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        # "NAME": "vm_test2",
        "NAME": "vm4",
        "USER": "vm",
        "PASSWORD": "123456",
        "HOST": "192.168.1.21",
        # "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True
# django项目的settings.py文件中设置了USE_TZ = True, 所以会有这个警告. 如果你将其设置为False就不会有这个警告了. 但首先你要确定你的应用是否需要考虑时区问题.
# USE_TZ = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "[%(asctime)s] %(message)s"}},
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        }
    },
    "loggers": {"django": {"handlers": ["console"], "level": "DEBUG"}},
}
